version: "3.7"
volumes:
  database:
services:
  db:
    image: mysql:latest
    container_name: menu-backoffice-db
    ports:
      - 3309:3309
    volumes:
      - database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=hibernate
      - MYSQL_DATABASE=hibernate
      - MYSQL_USER=hibernate
      - MYSQL_PASSWORD=hibernate